### ISSUE TITLE
Making navbar sticky and applying glassmorphism on scrolling

### ISSUE THREAD

**Issue by NateNear** [yusuf57rl/skriza#13]
![image](https://github.com/yusuf57rl/skriza/assets/92938055/51153db2-091b-4c81-93d0-221f07371eaa)

### TO THIS

![image](https://github.com/yusuf57rl/skriza/assets/92938055/b52f553b-6f5e-40c4-ab30-515357b0b9b1)

**Comment by yusuf57rl** [comment]
Hi @NateNear , thanks for the suggestion about making the navbar sticky and applying glassmorphism. Just a quick note: the website you're seeing right now is a temporary version. We're in the process of developing the full Skriza website, available on GitHub, which will soon replace this one. The new site will address many of these UI/UX issues. Thanks for your understanding!
