### ISSUE TITLE
Improving the carousel

### ISSUE THREAD

**Issue by NateNear** [yusuf57rl/skriza#14]
![image](https://github.com/yusuf57rl/skriza/assets/92938055/7e494b05-0189-4018-9802-b6d00c0edc86)

**Comment by yusuf57rl** [comment]
Hi @NateNear , thanks for your suggestion about improving the carousel. Just to set expectations, the current website is a transitional placeholder. We're actively working on the full version of the Skriza site, which you can find on GitHub. That version will soon replace the current site, and it will include a more polished user experience. We appreciate your input and patience!
