### ISSUE TITLE
Hover feature not working on Discord

### ISSUE THREAD

**Issue by NateNear** [yusuf57rl/skriza#15]
![image](https://github.com/yusuf57rl/skriza/assets/92938055/93bbfba2-126e-47f3-b97a-b26020f8d293)

**Comment by GD0910** [comment]
hi @NateNear , is the discord button not working or just a hower problem

**Comment by NateNear** [comment]
just a hover problem

**Comment by GD0910** [comment]
ok thank you for the update will check from my side as well

**Comment by yusuf57rl** [comment]
Hi all, thanks for pointing out the hover issue on Discord. Just to clarify, the current website is a temporary placeholder as we're in active development. The full-fledged Skriza site, which is also on GitHub, will be deployed soon to replace it. We appreciate your patience and understanding.
